/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_4 (
    input clk,
    input rst,
    input [7:0] a,
    input [7:0] b,
    input [0:0] in,
    output reg [15:0] mul
  );
  
  
  
  always @* begin
    
    case (in[0+0-:1])
      1'h0: begin
        mul = a * b;
      end
      1'h1: begin
        mul = a / b;
      end
      default: begin
        mul = a * b;
      end
    endcase
  end
endmodule
